In [1]:
a = 12
if a%2==0:
    print("even")
else: print("odd")   

even


In [2]:
def factorial(num):
    x = 1
    for i in range(num):
        x = x*(i+1)
    print(x)

In [3]:
factorial(5)

120


In [4]:
a = []
for i in range(1, 101):
    if i%2==0:
        a.append(i)

In [5]:
st = "hello world".lower()
vowel = ['a','e','i','o','u']
count = 0
for i in st:
    if i in vowel:
        count +=1
print(count)        

3


In [6]:
reversed_st = ""
for i in st:
    reversed_st = i + reversed_st
print(reversed_st)

dlrow olleh


# lambda Function

In [7]:
x = lambda x : x+3
x(7)


10

In [8]:
def my_func(n):
    return lambda a : a+n
my_sum = my_func(5)


In [9]:
my_sum(4)

9

# Advanced Functions


In [10]:
map_output = list(map(lambda x : x+3, [1,2,3,4]))

In [11]:
print(map_output)

[4, 5, 6, 7]


In [12]:
filter_output = list(filter(lambda x: x%2 == 0, [1,2,3,4,5,6,7,8,9,10]))

In [13]:
filter_output

[2, 4, 6, 8, 10]

In [14]:
import functools
reduce_output = functools.reduce(lambda a, x: a+x, [1,2,3,4,5,6,7,8,9,10])

In [15]:
reduce_output

55

In [16]:
def outer_func(msg):
    message = msg
    def inner_func():
        print(message)
        return inner_func

In [17]:
my_func = outer_func("Hello")

In [18]:
def simple_generator(n):
    i = 0
    while i < n:
        yield i
        i += 1


s = simple_generator(5)

for i in s:
    print(i)
# Using the generator
# gen = simple_generator
# gen(5)

0
1
2
3
4


In [19]:
lst = [3,5,5,23,5,6]

l = iter(lst)
l
# print(next(l))
# print(next(l))
# print(next(l))
# print(next(l))
# print(next(l))
# print(next(l))

In [20]:
next(iter(l))

3

In [21]:


def simple_generator(n):
    i = 0
    while i < n:
        yield i
        i += 1
gen = simple_generator(5)  # it is storing values somewhere but not print it cuz of yield used here so we can iterate over it 

In [22]:
for num in gen:
    print(num)

0
1
2
3
4


# Decorators

In [23]:
users = {
    'AI':'Jarvis',
    'Work' : 'ML'
}
for i in users:
    print(i)

AI
Work


In [24]:
def show(username, password):
    if username in users and users[username] == password:
        print("Authenticated")
    else:
        print("Not authenticated")

In [25]:
show('AI', 'Jarvis')

Authenticated


In [26]:
def add(username, password, a, b):
    if username in users and users[username] == password:
        print(a+b)
    else:
        print("Authentication required")

In [27]:
add('AI','Jarvis', 2, 3)

5


In [28]:
users

{'AI': 'Jarvis', 'Work': 'ML'}

In [29]:
def add(a, b):
    print(a+b)

In [30]:
def login_req(f):
    def wrapper(username, password, *args, **kwargs):
        if username in users and users[username] == password:
            f(*args, **kwargs)
        else:
            print("Not authenticated")
    return wrapper        

In [31]:
add = login_req(add)

In [32]:
protec_add = login_req(add)

In [33]:
print(add(2, 3))

Not authenticated
None


In [34]:
protec_add('AI', 'Jarvis',2,3)

Not authenticated


In [35]:
add('AI', 'Jarvis',2,3)

5


In [36]:
# Strings
# list
# Tuples
# Dictionart
# set

In [37]:
# Strings

In [38]:
st = 'Dogs are always loyal with humans'
print(type(st))

<class 'str'>


In [39]:
st.count('D')  # count how many times D letter is repeating in string

1

In [40]:
st.count('loyal')

1

In [41]:
st.count('s')

3

In [42]:
st.replace("Dogs","Only Dogs")

'Only Dogs are always loyal with humans'

In [43]:
st.replace('s','T')  # change will happend in S in string

'DogT are alwayT loyal with humanT'

In [44]:
st.upper()

'DOGS ARE ALWAYS LOYAL WITH HUMANS'

In [45]:
st.lower()

'dogs are always loyal with humans'

In [46]:
ord('c') # return me the ascii code for c

99

In [47]:
ord("A")

65

In [48]:
chr(ord("A"))

'A'

In [49]:
chr(65+32)

'a'

In [50]:
chr(ord('A') + 32)

'a'

In [51]:
st 

'Dogs are always loyal with humans'

In [52]:
st_upper = ""
for i in st.lower():
    if i == " ":
        pass
    else:
        st_upper = st_upper + chr(ord(i) - 32)

In [53]:
st_upper

'DOGSAREALWAYSLOYALWITHHUMANS'

In [54]:
st = st.lower()
st
# lower_st = st.split()
# lower_st


'dogs are always loyal with humans'

In [55]:
st

'dogs are always loyal with humans'

In [56]:
st[0]

'd'

In [57]:
st[::-1] # reverse a string

'snamuh htiw layol syawla era sgod'

In [58]:
st[: 11]

'dogs are al'

In [59]:
st[18:]

'yal with humans'

In [60]:
st.isalpha() # check for only alphabets is present or not?

False

In [61]:
st.endswith('humans') # whether a string ends with the character or text

True

In [62]:
st.capitalize()  # Make first letter as capital 

'Dogs are always loyal with humans'

In [63]:
st.find('humans')  # find the position of character or any text index will be return

27

In [64]:
# st.


In [65]:
# List

In [66]:
a = ['Tushar', 1, 2,3.4, True, range(1, 10), [1,2,3,4]]
type(a)

list

In [67]:
for i in a:
    print(i)

Tushar
1
2
3.4
True
range(1, 10)
[1, 2, 3, 4]


In [68]:
a[0]

'Tushar'

In [69]:
a[1]

1

In [70]:
a[2]

2

In [71]:
a[3]

3.4

In [72]:
a[4]

True

In [73]:
a[5]

range(1, 10)

In [74]:
for i in a[5]:
    print(i)

1
2
3
4
5
6
7
8
9


In [75]:
a[6]

[1, 2, 3, 4]

In [76]:
a[6][2]

3

In [77]:
a.append('Hi')  # add hi in the last of the list

In [78]:
a

['Tushar', 1, 2, 3.4, True, range(1, 10), [1, 2, 3, 4], 'Hi']

In [79]:
a.insert(1, 'Khitoliya')  # add the element at the specific index given here

In [80]:
a

['Tushar', 'Khitoliya', 1, 2, 3.4, True, range(1, 10), [1, 2, 3, 4], 'Hi']

In [81]:
st

'dogs are always loyal with humans'

In [82]:
l = []
n = 0
for i in range(len(st)):
    if st[i] == " ":
        l.append(st[n:i])
        n = i+1

In [83]:
l

['dogs', 'are', 'always', 'loyal', 'with']

In [84]:
a.pop()  # remove the element from the last

'Hi'

In [85]:
a  # hi will be removed and returned by the pop function and can be removed from any specific index

['Tushar', 'Khitoliya', 1, 2, 3.4, True, range(1, 10), [1, 2, 3, 4]]

In [86]:
a.pop(-2)

range(1, 10)

In [87]:
a.remove(1)

In [88]:
a

['Tushar', 'Khitoliya', 2, 3.4, True, [1, 2, 3, 4]]

In [89]:
a.reverse()

In [90]:
a

[[1, 2, 3, 4], True, 3.4, 2, 'Khitoliya', 'Tushar']

In [91]:
# backend of reverse

In [92]:
l = []
for i in a:
    l.insert(0, i)

In [93]:
l

['Tushar', 'Khitoliya', 2, 3.4, True, [1, 2, 3, 4]]

In [94]:
sorted(a[5], reverse = True)

['u', 's', 'r', 'h', 'a', 'T']

In [95]:
a.index('Tushar')  # find the index of any element by index

5

In [96]:
# find the occurence of each character in a string
st

'dogs are always loyal with humans'

In [97]:
b = []
c = st.upper()
for i in c:
    if i not in b:
        b.append(i)
        print('no of occurence : ', i, c.count(i))

no of occurence :  D 1
no of occurence :  O 2
no of occurence :  G 1
no of occurence :  S 3
no of occurence :    5
no of occurence :  A 5
no of occurence :  R 1
no of occurence :  E 1
no of occurence :  L 3
no of occurence :  W 2
no of occurence :  Y 2
no of occurence :  I 1
no of occurence :  T 1
no of occurence :  H 2
no of occurence :  U 1
no of occurence :  M 1
no of occurence :  N 1


In [98]:
# Tuple

In [99]:
tup = (2, 3,3.4, True, range(0, 10), [1,2,3,4.5])

In [100]:
# new_tup = tup + 1

In [101]:
new_tup = tup + (1, )

In [102]:
new_tup

(2, 3, 3.4, True, range(0, 10), [1, 2, 3, 4.5], 1)

In [103]:
new_tup = list(new_tup)  #now perform any function do any manipulation

In [104]:
# Dictionary
dic = {
    'a' : 'First element',
    'b' : 'second element',
    'c' : 32,
    'd' : {
        'Hello' : 41,
        'Tushar' : True
    },
    'e' : [1.2,2,3,4,5.6]
}

In [105]:
dic.items()

dict_items([('a', 'First element'), ('b', 'second element'), ('c', 32), ('d', {'Hello': 41, 'Tushar': True}), ('e', [1.2, 2, 3, 4, 5.6])])

In [106]:
for i in dic.items():
    print(i)

('a', 'First element')
('b', 'second element')
('c', 32)
('d', {'Hello': 41, 'Tushar': True})
('e', [1.2, 2, 3, 4, 5.6])


In [107]:
for i in dic.items():
    print(i[0])  # will print all the keys

a
b
c
d
e


In [108]:
for i in dic.items():
    print(i[1])  # will print all the values 

First element
second element
32
{'Hello': 41, 'Tushar': True}
[1.2, 2, 3, 4, 5.6]


In [109]:
dic.get('e')   # we need to pass only the key here to find the value of that particular key

[1.2, 2, 3, 4, 5.6]

In [110]:
dic.keys()  # print all the keys in a dictionary

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [111]:
dic.values()  # print all the values of their respective keys

dict_values(['First element', 'second element', 32, {'Hello': 41, 'Tushar': True}, [1.2, 2, 3, 4, 5.6]])

In [112]:
# Print only those values which is a dictionary  accessing the True value only
for i in dic.values():
    if isinstance(i, dict):
        for j in i.values():
            if isinstance(j, bool):
                print(j)

True


In [113]:
for i in dic.keys():
    print(i)

a
b
c
d
e


In [114]:
dic['a']  # here 'a' is a key to access directly the value of this value

'First element'

In [115]:
dic['b']

'second element'

In [116]:
dic['e']

[1.2, 2, 3, 4, 5.6]

# Numpy Linear Algebra

In [117]:
import numpy as np
from numpy import linalg as ln

In [118]:
a = np.array([[1, 2], 
              [2, 4]])
b = np.array([3, 4])

In [119]:
np.dot(a, b)

array([11, 22])

In [120]:
np.dot(b, a)

array([11, 22])

In [121]:
a = np.array([[1,2], 
             [4, 4]])
b = np.array([[3,4],
              [5, 6]])

In [122]:
np.dot(a,b)

array([[13, 16],
       [32, 40]])

In [123]:
import numpy as np

def adjoint(A):
    A = np.array(A)
    n = A.shape[0]
    cofactors = np.zeros_like(A, dtype=float)

    for i in range(n):
        for j in range(n):
            # Minor matrix after removing i-th row and j-th column
            minor = np.delete(np.delete(A, i, axis=0), j, axis=1)
            cofactors[i][j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    
    return cofactors.T  # Transpose of the cofactor matrix

# Example usage:
A = np.array([[1, 2], [3, 4]])
adj = adjoint(A)
print(adj)


[[ 4. -2.]
 [-3.  1.]]


In [124]:
ln.det(A)

-2.0000000000000004

In [125]:
inverse_A = (adj)/ln.det(A)

In [126]:
inverse_A

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [127]:
A

array([[1, 2],
       [3, 4]])

In [128]:
ln.inv(A)  # inverse of a matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [129]:
ln.det(a)

-4.0

In [130]:
# b = np.array([1.2, 3.4])
x = ln.solve(a, b)  # it may take only vector for second matrix but if we had a 2x2 matrix it will find equation for every possible row in the second matrix

In [131]:
x

array([[-0.5 , -1.  ],
       [ 1.75,  2.5 ]])

In [132]:
a

array([[1, 2],
       [4, 4]])

In [133]:
eig_value, eig_vector = ln.eig(a)

In [134]:
eig_value

array([-0.70156212,  5.70156212])

In [135]:
eig_vector

array([[-0.76164568, -0.39144501],
       [ 0.64799372, -0.9202015 ]])

In [136]:
u, s, vt = ln.svd(a)

In [137]:
print(u, s, vt)

[[-0.35538056 -0.9347217 ]
 [-0.9347217   0.35538056]] [6.04668437 0.66151956] [[-0.67710949 -0.73588229]
 [ 0.73588229 -0.67710949]]


In [138]:
norm_val = ln.norm(a)

In [139]:
norm_val

6.082762530298219

In [140]:
ln.matrix_rank(a)

2

In [141]:
a

array([[1, 2],
       [4, 4]])

In [142]:
# sum of diagonal element
np.trace(a)

5

In [143]:
a.T

array([[1, 4],
       [2, 4]])

In [144]:
np.transpose(a)

array([[1, 4],
       [2, 4]])

In [145]:
a.flatten()

array([1, 2, 4, 4])

In [146]:
rn_mat = np.random.random((3,2 ))

In [147]:
rn_mat[:2]

array([[0.44608155, 0.11997556],
       [0.37015553, 0.90367774]])

In [148]:
x = np.array(([1, 2],
             [3, 4]))
y = np.array([[4, 7],
              [3, 7]])

In [149]:
x+y

array([[ 5,  9],
       [ 6, 11]])

In [150]:
x-y

array([[-3, -5],
       [ 0, -3]])

In [151]:
x*y

array([[ 4, 14],
       [ 9, 28]])

In [152]:
x/y

array([[0.25      , 0.28571429],
       [1.        , 0.57142857]])

In [153]:
np.add(x, y)

array([[ 5,  9],
       [ 6, 11]])

In [154]:
np.subtract(x, y)

array([[-3, -5],
       [ 0, -3]])

In [155]:
np.multiply(x,y)

array([[ 4, 14],
       [ 9, 28]])

In [156]:
np.divide(x, y)

array([[0.25      , 0.28571429],
       [1.        , 0.57142857]])

In [157]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [158]:
np.dot(x, y)

array([[10, 21],
       [24, 49]])

In [159]:
x@y

array([[10, 21],
       [24, 49]])

In [160]:
x.dot(y)

array([[10, 21],
       [24, 49]])

In [161]:
np.sum(x, axis = 0)

array([4, 6])

In [162]:
np.sum(x, axis = 1)

array([3, 7])

In [163]:
a 

array([[1, 2],
       [4, 4]])

In [164]:
b = a**2

In [165]:
b

array([[ 1,  4],
       [16, 16]])

In [166]:
stacked = np.stack((a,b), axis = 0)

In [167]:
stacked

array([[[ 1,  2],
        [ 4,  4]],

       [[ 1,  4],
        [16, 16]]])

In [168]:
stacked = np.stack((b,a), axis = 1)

In [169]:
stacked

array([[[ 1,  4],
        [ 1,  2]],

       [[16, 16],
        [ 4,  4]]])

In [170]:
a.shape

(2, 2)

In [171]:
rn_mat.shape

(3, 2)

In [172]:
rn_mat.T.shape

(2, 3)

In [173]:
rn_mat.reshape(3,-1)

array([[0.44608155, 0.11997556],
       [0.37015553, 0.90367774],
       [0.58929914, 0.94379816]])

In [174]:
np.random.shuffle(rn_mat)

In [175]:
rn_mat

array([[0.37015553, 0.90367774],
       [0.44608155, 0.11997556],
       [0.58929914, 0.94379816]])

In [176]:
np.random.rand(2, 3)

array([[0.6439794 , 0.0770055 , 0.48052783],
       [0.04574668, 0.03826015, 0.30982999]])

In [177]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [178]:
np.random.randint(100, 10000, 100)

array([9193, 5115, 5051, 9218, 2729, 4704, 5222, 9905, 2707, 9869, 3307,
       7402, 1109, 5516, 1094, 9079, 4544, 2167, 3094, 2497, 2237, 4275,
        152, 9515, 9576, 6601, 5903, 7700, 5461, 3195, 5941, 3412, 6874,
       5070, 9927, 7431, 8422, 1024, 6916, 7519, 4170, 1185, 3267, 1172,
       2185, 4528, 1439, 2294, 8334, 9928, 9681, 5633, 5102, 4574,  504,
        887, 4587, 9171, 5235,  292, 5455, 2206, 7924, 7095, 5080, 6351,
       9977, 2603, 4514, 4232, 1580, 7286, 1007,  537, 1572, 7417, 4570,
       7688, 5615, 9731, 6976, 9588, 9894, 6615, 6537, 7449, 2194, 1547,
       6714, 8987, 6902, 4247, 8349, 5547, 4808, 2498, 5880, 4671, 5436,
       1741])

In [179]:
np.random.randint(5, 100, (5,10))

array([[94, 74, 32, 89, 15, 25, 57, 46, 52, 59],
       [29, 38, 31, 74, 69, 30, 87, 13, 49,  9],
       [89, 25, 20, 47, 94,  9,  6, 60,  8, 93],
       [41, 99, 65, 45, 89, 16, 61, 42, 21, 86],
       [79, 59, 55, 64, 83, 90, 69, 29, 99, 36]])

In [180]:
arr = np.random.randint(5, 100, 10)

In [181]:
arr

array([93, 53, 95, 40, 33, 86, 29, 52, 62, 40])

In [182]:
np.random.shuffle(arr)

In [183]:
np.random.choice(arr)

33

In [184]:
a

array([[1, 2],
       [4, 4]])

In [185]:
np.min(a)

1

In [186]:
np.min(a, axis = 0)

array([1, 2])

In [187]:
a = np.array([[1,2,5,3], 
              [6,2,3,4]])

In [188]:
np.min(a)

1

In [189]:
np.min(a, axis = 0)

array([1, 2, 3, 3])

In [190]:
np.min(a, axis = 1)

array([1, 2])

In [191]:
np.mean(a)

3.25

In [192]:
u = np.mean(a, axis = 0)

In [193]:
u

array([3.5, 2. , 4. , 3.5])

In [194]:
from numpy import linalg as ln

In [195]:
a,b

(array([[1, 2, 5, 3],
        [6, 2, 3, 4]]),
 array([[ 1,  4],
        [16, 16]]))

In [196]:
np.dot(a[:,2:], b)

array([[53, 68],
       [67, 76]])

In [197]:
ln.inv(b)  # inverse only and only for a square matrix

array([[-0.33333333,  0.08333333],
       [ 0.33333333, -0.02083333]])

In [198]:
ln.det(b)

-47.999999999999986

In [199]:
x = ln.solve(a[:, :2], b)

In [200]:
x

array([[ 3. ,  2.4],
       [-1. ,  0.8]])

In [201]:
eig_value , eig_vector = ln.eig(b)

In [202]:
eig_value, eig_vector

(array([-2.4658561, 19.4658561]),
 array([[-0.75576488, -0.21170605],
        [ 0.65484308, -0.97733339]]))

In [203]:
ln.norm(b)

23.0

In [204]:
ln.matrix_rank(b)

2

In [205]:
np.trace(b)

17

In [206]:
a.flatten()

array([1, 2, 5, 3, 6, 2, 3, 4])

In [207]:
a.reshape(-1, 2)

array([[1, 2],
       [5, 3],
       [6, 2],
       [3, 4]])

In [208]:
a.T

array([[1, 6],
       [2, 2],
       [5, 3],
       [3, 4]])

# Pandas

In [340]:
import pandas as pd

In [341]:
df = pd.read_csv('Titanic-Dataset.csv')

In [342]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [343]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [344]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [345]:
wine_ = pd.read_csv('wine.csv')

In [346]:
grouped = df.groupby('Sex').size()   # size means strength of each category
print(grouped)

Sex
female    314
male      577
dtype: int64


In [347]:
appended_data = pd.concat([df, wine_], ignore_index= True)

In [348]:
appended_data

PassengerId  Survived  Pclass  \
0             1.0       0.0     3.0   
1             2.0       1.0     1.0   
2             3.0       1.0     3.0   
3             4.0       1.0     1.0   
4             5.0       0.0     3.0   
...           ...       ...     ...   
1064          NaN       NaN     NaN   
1065          NaN       NaN     NaN   
1066          NaN       NaN     NaN   
1067          NaN       NaN     NaN   
1068          NaN       NaN     NaN   

                                                   Name     Sex   Age  SibSp  \
0                               Braund, Mr. Owen Harris    male  22.0    1.0   
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                                Heikkinen, Miss. Laina  female  26.0    0.0   
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                              Allen, Mr. William Henry    male  35.0    0.0   
...                                                 ...     ...   ...    ...   
1064                                                NaN     NaN   NaN    NaN   
1065                                                NaN     NaN   NaN    NaN   
1066                                                NaN     NaN   NaN    NaN   
1067                                                NaN     NaN   NaN    NaN   
1068                                                NaN     NaN   NaN    NaN   

      Parch            Ticket     Fare  ...   Acl     Mg  Phenols  Flavanoids  \
0       0.0         A/5 21171   7.2500  ...   NaN    NaN      NaN         NaN   
1       0.0          PC 17599  71.2833  ...   NaN    NaN      NaN         NaN   
2       0.0  STON/O2. 3101282   7.9250  ...   NaN    NaN      NaN         NaN   
3       0.0            113803  53.1000  ...   NaN    NaN      NaN         NaN   
4       0.0            373450   8.0500  ...   NaN    NaN      NaN         NaN   
...     ...               ...      ...  ...   ...    ...      ...         ...   
1064    NaN               NaN      NaN  ...  20.5   95.0     1.68        0.61   
1065    NaN               NaN      NaN  ...  23.0  102.0     1.80        0.75   
1066    NaN               NaN      NaN  ...  20.0  120.0     1.59        0.69   
1067    NaN               NaN      NaN  ...  20.0  120.0     1.65        0.68   
1068    NaN               NaN      NaN  ...  24.5   96.0     2.05        0.76   

      Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                      NaN      NaN        NaN   NaN   NaN      NaN  
1                      NaN      NaN        NaN   NaN   NaN      NaN  
2                      NaN      NaN        NaN   NaN   NaN      NaN  
3                      NaN      NaN        NaN   NaN   NaN      NaN  
4                      NaN      NaN        NaN   NaN   NaN      NaN  
...                    ...      ...        ...   ...   ...      ...  
1064                  0.52     1.06        7.7  0.64  1.74    740.0  
1065                  0.43     1.41        7.3  0.70  1.56    750.0  
1066                  0.43     1.35       10.2  0.59  1.56    835.0  
1067                  0.53     1.46        9.3  0.60  1.62    840.0  
1068                  0.56     1.35        9.2  0.61  1.60    560.0  

[1069 rows x 26 columns]

In [349]:
pd.concat([df, wine_], axis = 1)   # column wise adding

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare  ...   Acl     Mg  Phenols  Flavanoids  \
0        0         A/5 21171   7.2500  ...  15.6  127.0     2.80        3.06   
1        0          PC 17599  71.2833  ...  11.2  100.0     2.65        2.76   
2        0  STON/O2. 3101282   7.9250  ...  18.6  101.0     2.80        3.24   
3        0            113803  53.1000  ...  16.8  113.0     3.85        3.49   
4        0            373450   8.0500  ...  21.0  118.0     2.80        2.69   
..     ...               ...      ...  ...   ...    ...      ...         ...   
886      0            211536  13.0000  ...   NaN    NaN      NaN         NaN   
887      0            112053  30.0000  ...   NaN    NaN      NaN         NaN   
888      2        W./C. 6607  23.4500  ...   NaN    NaN      NaN         NaN   
889      0            111369  30.0000  ...   NaN    NaN      NaN         NaN   
890      0            370376   7.7500  ...   NaN    NaN      NaN         NaN   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.92   1065.0  
1                    0.26     1.28       4.38  1.05  3.40   1050.0  
2                    0.30     2.81       5.68  1.03  3.17   1185.0  
3                    0.24     2.18       7.80  0.86  3.45   1480.0  
4                    0.39     1.82       4.32  1.04  2.93    735.0  
..                    ...      ...        ...   ...   ...      ...  
886                   NaN      NaN        NaN   NaN   NaN      NaN  
887                   NaN      NaN        NaN   NaN   NaN      NaN  
888                   NaN      NaN        NaN   NaN   NaN      NaN  
889                   NaN      NaN        NaN   NaN   NaN      NaN  
890                   NaN      NaN        NaN   NaN   NaN      NaN  

[891 rows x 26 columns]

In [350]:
x = np.arange(16.0).reshape(4, 4)

In [351]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [352]:
print(x, '\n')

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] 



In [353]:
print(np.hsplit(x, 2), '\n\n')

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])] 




In [354]:
print(np.hsplit(x, np.array([3, 6])))

[array([[ 0.,  1.,  2.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.],
       [12., 13., 14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]]), array([], shape=(4, 0), dtype=float64)]


In [355]:
np.linspace(0, 100, 5) # generate equally spaced value in the intervals

array([  0.,  25.,  50.,  75., 100.])

# pandas 

In [356]:
import pandas as pd
df = pd.read_csv('Titanic-Dataset.csv')

In [357]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [358]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [359]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [360]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [361]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [362]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [363]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [364]:
df['Age'] = df['Age'].fillna(df['Age'].mean)

In [365]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].value_counts().idxmax())

In [366]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [367]:
df.drop(columns = ['PassengerId','Name','Ticket','Cabin'], inplace=True)

In [368]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [369]:
# df[df['Sex'] == 'male']['Fare']*0.9

In [370]:
7.2500*0.9

6.525

In [371]:
8.0500*0.9

7.245000000000001

In [372]:
71.2833*0.2 + 57.02664

71.2833

In [373]:
import warnings
warnings.filterwarnings('ignore')

In [374]:
for i in range(df.shape[0]):
    if df['Sex'][i] == 'male':
        df['Fare'][i] = df['Fare'][i]*0.9
    else:
        df['Fare'][i] = df['Fare'][i]*0.8

In [375]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         0       3    male  22.0      1      0   6.52500        S
1         1       1  female  38.0      1      0  57.02664        C
2         1       3  female  26.0      0      0   6.34000        S
3         1       1  female  35.0      1      0  42.48000        S
4         0       3    male  35.0      0      0   7.24500        S

In [247]:
df['Embarked'].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [248]:
df['Embarked'] = df['Embarked'].map({'S':0, 'C':1, 'Q':2})

In [249]:
# def encoding(x):
#     if x == 'male':
#         return 0
#     elif x == 'female':
#         return 1
#     elif x == 'S':
#         return 0
#     elif x == 'C':
#         return 1
#     elif x == 'Q':
#         return 2
#     else:
#         pass
# df['Sex']  = df['Sex'].map(encoding)
# df['Embarked'] = df['Embarked'].map(encoding)

In [250]:
df['Sex'] = df['Sex'].map({'male': 0, 'female' : 1})

In [251]:
# lets seperate the Fare after the decimal value

In [252]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    object 
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64  
dtypes: float64(1), int64(6), object(1)
memory usage: 55.8+ KB


In [376]:
for i in range(df.shape[0]):
    df['Fare_1'] =(df['Fare'].astype('str')[i]).split('.')[0]
    df['Fare_2'] = (df['Fare'].astype('str')[i]).split('.')[1]

In [377]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked Fare_1  \
0         0       3    male  22.0      1      0   6.52500        S      6   
1         1       1  female  38.0      1      0  57.02664        C      6   
2         1       3  female  26.0      0      0   6.34000        S      6   
3         1       1  female  35.0      1      0  42.48000        S      6   
4         0       3    male  35.0      0      0   7.24500        S      6   

             Fare_2  
0  9750000000000005  
1  9750000000000005  
2  9750000000000005  
3  9750000000000005  
4  9750000000000005

In [378]:
pivot = pd.pivot_table(df, values = 'Fare', index = 'Pclass', columns = 'Survived', aggfunc= 'mean')

In [379]:
pivot # means you want to see the categorically change in any numerical values on the basis of their mean, avg,sum etc values 

Survived          0          1
Pclass                        
1         57.800841  78.956040
2         17.358208  18.056763
3         11.919723  11.571242

In [380]:
df.head(1)

Survived  Pclass   Sex   Age  SibSp  Parch   Fare Embarked Fare_1  \
0         0       3  male  22.0      1      0  6.525        S      6   

             Fare_2  
0  9750000000000005

In [381]:
pd.pivot_table(df, values = 'Age', index = 'Sex', columns = 'Survived', aggfunc = 'count')

Survived    0    1
Sex               
female     81  233
male      468  109

In [382]:
pd.pivot_table(df, values = ['Age','Fare'], index = 'Pclass', columns = 'Survived', aggfunc = 'count')

Age      Fare     
Survived    0    1    0    1
Pclass                      
1          80  136   80  136
2          97   87   97   87
3         372  119  372  119

In [383]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    object 
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object 
 8   Fare_1    891 non-null    object 
 9   Fare_2    891 non-null    object 
dtypes: float64(1), int64(4), object(5)
memory usage: 69.7+ KB


In [384]:
# df['AgeGroup'] = df['Age'].apply(lambda x: 'Adult' if int(x) >= 18 else 'Child')

In [385]:
company = list(df['SibSp'] + df['Parch'])

In [386]:
df.insert(4, 'Company', company)  # insert into the dataframe at specific position

In [387]:
df.head(2)

Survived  Pclass     Sex   Age  Company  SibSp  Parch      Fare Embarked  \
0         0       3    male  22.0        1      1      0   6.52500        S   
1         1       1  female  38.0        1      1      0  57.02664        C   

  Fare_1            Fare_2  
0      6  9750000000000005  
1      6  9750000000000005

In [388]:
df.ndim

2

In [389]:
data = pd.DataFrame({
    'Price': ['$10.00', '$15.50', '$20.75']
})


In [390]:
data

Price
0  $10.00
1  $15.50
2  $20.75

In [391]:
data['Price_clean'] = data['Price'].apply(lambda x: float(x.replace('$','')))

In [392]:
data.head()

Price  Price_clean
0  $10.00        10.00
1  $15.50        15.50
2  $20.75        20.75

In [393]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Company     0
SibSp       0
Parch       0
Fare        0
Embarked    0
Fare_1      0
Fare_2      0
dtype: int64

In [394]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [395]:
d1 = pd.DataFrame({'A': [1,2,3,4,5], 'B': [6,7,8,9,10]})
d2 = pd.DataFrame({'C': [11,12,13,14,15], 'D': [16,17,18,19,20]})

In [396]:
d1

A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [397]:
d2

C   D
0  11  16
1  12  17
2  13  18
3  14  19
4  15  20

In [398]:
col = pd.concat([d1, d2], axis = 1)

In [399]:
col

A   B   C   D
0  1   6  11  16
1  2   7  12  17
2  3   8  13  18
3  4   9  14  19
4  5  10  15  20

In [400]:
d1 = pd.DataFrame({'A': [1,2,3,4,5], 'B': [6,7,8,9,10]})
d2 = pd.DataFrame({'C': [11,12,13,14,15], 'D': [16,17,18,19,20], 'A': [1, 2, 3, 4, 5]})

In [401]:
d1

A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [402]:
d2

C   D  A
0  11  16  1
1  12  17  2
2  13  18  3
3  14  19  4
4  15  20  5

In [403]:
pd.merge(d1, d2, on='A')

A   B   C   D
0  1   6  11  16
1  2   7  12  17
2  3   8  13  18
3  4   9  14  19
4  5  10  15  20

In [404]:
df.groupby('Sex').size()

Sex
female    314
male      577
dtype: int64

In [405]:
df.groupby('Embarked').size()

Embarked
C    168
Q     77
S    646
dtype: int64

In [411]:
d = df.groupby('Sex')

In [444]:
d.get_group('male')

Survived  Pclass   Sex  \
0           0       3  male   
4           0       3  male   
5           0       3  male   
6           0       1  male   
7           0       3  male   
..        ...     ...   ...   
883         0       2  male   
884         0       3  male   
886         0       2  male   
889         1       1  male   
890         0       3  male   

                                                   Age  Company  SibSp  Parch  \
0                                                 22.0        1      1      0   
4                                                 35.0        0      0      0   
5    <bound method Series.mean of 0      22.0\n1   ...        0      0      0   
6                                                 54.0        0      0      0   
7                                                  2.0        4      3      1   
..                                                 ...      ...    ...    ...   
883                                               28.0        0      0      0   
884                                               25.0        0      0      0   
886                                               27.0        0      0      0   
889                                               26.0        0      0      0   
890                                               32.0        0      0      0   

         Fare Embarked Fare_1            Fare_2  
0     6.52500        S      6  9750000000000005  
4     7.24500        S      6  9750000000000005  
5     7.61247        Q      6  9750000000000005  
6    46.67625        S      6  9750000000000005  
7    18.96750        S      6  9750000000000005  
..        ...      ...    ...               ...  
883   9.45000        S      6  9750000000000005  
884   6.34500        S      6  9750000000000005  
886  11.70000        S      6  9750000000000005  
889  27.00000        C      6  9750000000000005  
890   6.97500        Q      6  9750000000000005  

[577 rows x 11 columns]

In [445]:
f[f['Pclass'] == 2]

Survived  Pclass   Sex  \
17          1       2  male   
20          0       2  male   
21          1       2  male   
33          0       2  male   
70          0       2  male   
..        ...     ...   ...   
848         0       2  male   
861         0       2  male   
864         0       2  male   
883         0       2  male   
886         0       2  male   

                                                   Age  Company  SibSp  Parch  \
17   <bound method Series.mean of 0      22.0\n1   ...        0      0      0   
20                                                35.0        0      0      0   
21                                                34.0        0      0      0   
33                                                66.0        0      0      0   
70                                                32.0        0      0      0   
..                                                 ...      ...    ...    ...   
848                                               28.0        1      0      1   
861                                               21.0        1      1      0   
864                                               24.0        0      0      0   
883                                               28.0        0      0      0   
886                                               27.0        0      0      0   

      Fare Embarked Fare_1            Fare_2  
17   11.70        S      6  9750000000000005  
20   23.40        S      6  9750000000000005  
21   11.70        S      6  9750000000000005  
33    9.45        S      6  9750000000000005  
70    9.45        S      6  9750000000000005  
..     ...      ...    ...               ...  
848  29.70        S      6  9750000000000005  
861  10.35        S      6  9750000000000005  
864  11.70        S      6  9750000000000005  
883   9.45        S      6  9750000000000005  
886  11.70        S      6  9750000000000005  

[108 rows x 11 columns]

In [447]:
d['Fare'].get_group('male').sum()

13254.55785

In [448]:
d['Fare'].get_group('female').sum()

11173.330240000001

In [450]:
df['Fare'].sort_values()

179      0.00000
413      0.00000
466      0.00000
481      0.00000
302      0.00000
         ...    
438    236.70000
27     236.70000
258    409.86336
737    461.09628
679    461.09628
Name: Fare, Length: 891, dtype: float64